// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgG-Wj4bQ6LDmMPZ3Z40ddmi1Mw4lxRGA',
    appId: '1:720935335953:web:6aad56df34d3b9c6e059b0',
    messagingSenderId: '720935335953',
    projectId: 'gu-life-shift-management',
    authDomain: 'gu-life-shift-management.firebaseapp.com',
    storageBucket: 'gu-life-shift-management.appspot.com',
    measurementId: 'G-JNZYY503G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZHG3IMdCfsXR9IY4UvSM1zUmZ9w6ZNY',
    appId: '1:720935335953:android:dd6f60245c59bfc0e059b0',
    messagingSenderId: '720935335953',
    projectId: 'gu-life-shift-management',
    storageBucket: 'gu-life-shift-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb-FoS7-oudLGhnrGXQHLIaidUkPn8OBc',
    appId: '1:720935335953:ios:e16220096bc1cfebe059b0',
    messagingSenderId: '720935335953',
    projectId: 'gu-life-shift-management',
    storageBucket: 'gu-life-shift-management.appspot.com',
    iosBundleId: 'com.example.gulifeShiftManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb-FoS7-oudLGhnrGXQHLIaidUkPn8OBc',
    appId: '1:720935335953:ios:e16220096bc1cfebe059b0',
    messagingSenderId: '720935335953',
    projectId: 'gu-life-shift-management',
    storageBucket: 'gu-life-shift-management.appspot.com',
    iosBundleId: 'com.example.gulifeShiftManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgG-Wj4bQ6LDmMPZ3Z40ddmi1Mw4lxRGA',
    appId: '1:720935335953:web:062b88f29311bb22e059b0',
    messagingSenderId: '720935335953',
    projectId: 'gu-life-shift-management',
    authDomain: 'gu-life-shift-management.firebaseapp.com',
    storageBucket: 'gu-life-shift-management.appspot.com',
    measurementId: 'G-6208B4TPKM',
  );
}
